config/routes.rb
Statusbook::Application.routes.draw do
  get "profiles/show"
  devise_for :users

  devise_scope :user do
    get 'register', to: 'devise/registrations#new', as: :register
    get 'login', to: 'devise/sessions#new', as: :login
    get 'logout', to: 'devise/sessions#destroy', as: :logout
  end

  resources :statuses
  get 'feed', to: 'statuses#index', as: :feed

  root 'statuses#index'

  get '/:id', to: 'profiles#show'

end

app/models/status.rb
class Status < ActiveRecord::Base

  belongs_to :user

  validates :content, presence: true,
  					  length: { minimum: 3 }

  validates :user_id, presence: true

  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :statuses, dependent: :destroy

  validates :first_name, presence: true

  validates :last_name, presence: true
  
  validates :profile_name, presence: true, 
                          uniqueness: true,
                          format: { with: /\A[a-zA-Z][a-zA-Z0-9_-]+\z/, 
                          message: "must contains only letters, '-' or '_'."}

  def full_name
  	"#{first_name} #{last_name}"  	
  end

  def gravatar_url
    stripped_email = email.strip
    downcase_email = stripped_email.downcase
    hash = Digest::MD5.hexdigest(downcase_email)

    "http://gravatar.com/avatar/#{hash}?d=retro"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  #Strong parameters for Devise

  private

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, 
  		          :password_confirmation, :remeber_me, 
  				  :first_name, :last_name, :profile_name) }
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = User.find_by_profile_name(params[:id])
    if @user
      @statuses = @user.statuses.paginate(page: params[:page], per_page: 10)
      render action: :show
    else
      render 'public/404', status: 404, formats: [:html]
    end
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update]
  before_action :correct_user?, only: [:edit, :update]

  # GET /statuses
  # GET /statuses.json
  def index
    get_and_show_statuses
    #@statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
     respond_to do |format|
      format.html
      format.json { render json: @status }
    end
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render action: 'show', status: :created, location: @status }
      else
        format.html { render action: 'new' }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_status
    @status = Status.find(params[:id])
  end

  def correct_user?
    status = current_user.statuses.find_by(id: params[:id])
    redirect_to root_path if status.nil?
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def status_params
    params.require(:status).permit(:content, :user_id)
  end

  def get_and_show_statuses
    @statuses = Status.paginate(page: params[:page], per_page: 15).order('created_at DESC')
    respond_to do |format|
      format.html
      format.js
      format.json { render json: @statuses.as_json }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_class(type)
  	case type
  	when :notice
  		"alert-success"
  	when :alert
  		"alert-error"
  	else
  		""
  	end
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Statusbook</title>
		<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<div class="navbar navbar-fixed-top">
			<div class="navbar-inner">
				<div class="container">
					<%= link_to "Statusbook", root_path, class: "brand" %>					
					<ul class="nav pull-right">
						<li><%= link_to "All Statuses", feed_path %></li>
						<% if user_signed_in? %>
						<li><%= link_to current_user.full_name, edit_user_registration_path %> </li>
						<li> <%= link_to "Log Out", logout_path %> </li>
						<% else %>
						<li><%= link_to "Register", register_path %></li>
						<li><%= link_to "Sign In", login_path %></li>
						<% end %>
					</ul>
				</div>
			</div>
		</div>
		<div class="container">
			<% flash.each do |type, message| %>

			<div class="alert <%= flash_class(type) %>"> <%= message %> <button type="button" class="close" data-dismiss="alert">&times;</button></div>
			<% end %>
			<%= yield %>
		</div>
	</body>
</html>

app/views/profiles/_status.html.erb
<div class="well">
	<%= status.content  %>
	<hr />
	<%= link_to time_ago_in_words(status.created_at), status_path(status) %> ago
</div>

app/views/profiles/show.html.erb
<div class="page-header">
	<h1><%= image_tag @user.gravatar_url %> <%= @user.full_name %></h1>
</div>

<% if @statuses %>
<div class="statuses">
  <%= render @statuses %>
</div>
<% end %>

<% if @statuses.next_page %>
    <div id="load_more_statuses" class="btn btn-primary btn-lg">More statuses</div>
<% end %>

<div id="with-button">
    <%= will_paginate @statuses%>
</div>

app/views/profiles/show.js.erb
$('.statuses').append('<%= j render @statuses %>'); 
<% if @statuses.next_page %>
    $('.pagination').replaceWith('<%= j will_paginate @statuses %>');
$('.pagination').hide(); <%
else %>
    $('.pagination, #load_more_statuses').remove(); <% end %>

app/views/statuses/_form.html.erb
<%= simple_form_for(@status, html: { class: "form-horizontal" }) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>   
 
  <%= f.input :user_id, collection: User.all, label_method: :full_name %>
  <%= f.input :content %>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<div class="page-header">
  <h1>All Statuses</h1>
</div>
<div>
  <%= link_to "Post a new Status", new_status_path, class: "btn btn-primary" %>
</div><br />
<div class="statuses">
<%= render @statuses %>
</div>
<% if @statuses.next_page %>
    <div id="load_more_statuses" class="btn btn-primary btn-lg">More statuses</div>
<% end %>

<div id="with-button">
    <%= will_paginate %>
</div>

app/views/statuses/index.js.erb
$('.statuses').append('<%= j render @statuses %>'); 
<% if @statuses.next_page %>
    $('.pagination').replaceWith('<%= j will_paginate @statuses %>');
$('.pagination').hide(); <%
else %>
    $('.pagination, #load_more_statuses').remove(); <% end %>

app/views/statuses/new.html.erb
<h1>New status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @status.user.full_name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @status.content %>
</p>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>